In [1]:
import pandas as pd
from tkinter import *
import tkinter as tk 
import tkinter.messagebox
from tkinter import ttk

In [2]:
from forex_python.converter import CurrencyRates

In [3]:
df = pd.DataFrame({'country_name': ['BHUTAN','BRAZIL','BULGARIA','CANADA','CHINA','DENMARK','FRANCE','IRAN','USA','AUSTRALIA'],
                    'currency-code': ['BTN','BRL','BGN','CAD','CNY','DKK','EUR','IRR','USD','AUD'],
                     'indian_value' : ['1','16.08','42.39','60.41','11.62','11.12','80.53','546.8','77.53','54.89']} )

In [4]:

df

  country_name currency-code indian_value
0       BHUTAN           BTN            1
1       BRAZIL           BRL        16.08
2     BULGARIA           BGN        42.39
3       CANADA           CAD        60.41
4        CHINA           CNY        11.62
5      DENMARK           DKK        11.12
6       FRANCE           EUR        80.53
7         IRAN           IRR        546.8
8          USA           USD        77.53
9    AUSTRALIA           AUD        54.89

In [5]:
root = tk.Tk()
 
root.title("Currency converter")


Tops = Frame(root, bg = '#e6e5e5', pady=2, width=500, height=250, relief="ridge")
Tops.grid(row=0, column=0)
headlabel = tk.Label(Tops, font=('lato black', 14, 'bold'), text='CurrencyConverter:WELCOMEFOLKS',
                    bg='#e6e5e5', fg='black')
headlabel.grid(row=1, column=0, sticky=E)

In [6]:

variable1 = tk.StringVar(root)
variable2 = tk.StringVar(root)
 
variable1.set("currency")
variable2.set("currency")

In [7]:

def RealTimeCurrencyConversion():
    from forex_python.converter import CurrencyRates
    c = CurrencyRates()
 
    from_currency = variable1.get()
    to_currency = variable2.get()
 
    if (Amount1_field.get() == ""):
        tkinter.messagebox.showinfo("Error !!", "Amount Not Entered.\n Please a valid amount.")
 
    elif (from_currency == "currency" or to_currency == "currency"):
        tkinter.messagebox.showinfo("Error !!",
                                    "Currency Not Selected.\n Please select FROM and TO Currency form menu.")
 
    else:
        new_amt = c.convert(from_currency, to_currency, float(Amount1_field.get()))
        new_amount = float("{:.4f}".format(new_amt))
        Amount2_field.insert(0, str(new_amount))

In [8]:
def clear_all():
    Amount1_field.delete(0, tk.END)
    Amount2_field.delete(0, tk.END)
 
 
CurrenyCode_list = ["INR", "USD", "CAD", "CNY", "DKK", "EUR","BRL","AUD","BGN","BTN"]
 
root.configure(background='#e6e5e5')
root.geometry("700x400")
 
Label_1 = Label(root, font=('lato black', 27, 'bold'), text="", padx=2, pady=2, bg="#e6e5e5", fg="black")
Label_1.grid(row=1, column=0, sticky=W)
 
label1 = tk.Label(root, font=('lato black', 12, 'bold'), text="\tAmount  :  ", bg="#e6e5e5", fg="black")
label1.grid(row=2, column=0, sticky=W)
 
label1 = tk.Label(root, font=('lato black', 12, 'bold'), text="\tFrom Currency   ", bg="#e6e5e5", fg="black")
label1.grid(row=3, column=0, sticky=W)
 
label1 = tk.Label(root, font=('lato black', 12, 'bold'), text="\tTo Currency   ", bg="#e6e5e5", fg="black")
label1.grid(row=4, column=0, sticky=W)
 
label1 = tk.Label(root, font=('lato black', 12, 'bold'), text="\tConvertedAmount  :  ", bg="#e6e5e5", fg="black")
label1.grid(row=8, column=0, sticky=W)
 
Label_1 = Label(root, font=('lato black', 7, 'bold'), text="", padx=2, pady=2, bg="#e6e5e5", fg="black")
Label_1.grid(row=5, column=0, sticky=W)
 
Label_1 = Label(root, font=('lato black', 7, 'bold'), text="", padx=2, pady=2, bg="#e6e5e5", fg="black")
Label_1.grid(row=7, column=0, sticky=W)
 
FromCurrency_option = tk.OptionMenu(root, variable1, *CurrenyCode_list)
ToCurrency_option = tk.OptionMenu(root, variable2, *CurrenyCode_list)
 
FromCurrency_option.grid(row=3, column=0, ipadx=20, sticky=E)
ToCurrency_option.grid(row=4, column=0, ipadx=20, sticky=E)
 
Amount1_field = tk.Entry(root)
Amount1_field.grid(row=2, column=0, ipadx=28, sticky=E)
 
Amount2_field = tk.Entry(root)
Amount2_field.grid(row=8, column=0, ipadx=70, sticky=E)
 
Label_9 = Button(root, font=('arial', 15, 'bold'), text="   Convert  ", padx=2, pady=2, bg="black", fg="white",
                 command=RealTimeCurrencyConversion)
Label_9.grid(row=6, column=0)
 
Label_1 = Label(root, font=('lato black', 7, 'bold'), text="", padx=2, pady=2, bg="#e6e5e5", fg="black")
Label_1.grid(row=9, column=0, sticky=W)
 
Label_9 = Button(root, font=('arial', 15, 'bold'), text="   Clear All  ", padx=2, pady=2, bg="lightblue", fg="white",
                 command=clear_all)
Label_9.grid(row=10, columnspan=4)
 
 
root.mainloop()